user_pref("webgl.disabled", true);
user_pref("geo.enabled", false);
user_pref("geo.wifi.uri", "data:application/json,{"location": {"lat": 40.7590, "lng": -73.9845}, "accuracy": 27000.0}");
user_pref("network.prefetch-next", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("media.navigator.enabled", false);
user_pref("privacy.firstparty.isolate", true);
user_pref("privacy.resistFingerprinting", true);
user_pref("media.peerconnection.enabled", false);
user_pref("reader.parse-on-load.enabled", false);
user_pref("reader.parse-on-load.force-enabled", false);
